### ISSUE TITLE
Fails to build with v6.10 kernel

### ISSUE THREAD

**Issue by sudipm-mukherjee** [teddywlq/smifb2#20]
The build fails with the error:

```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_drv.c: In function 'smi_vram_suspend':
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_drv.c:234:27: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'? [-Werror=implicit-function-declaration]
  234 |         sdev->vram_save = vmalloc(vram_size << 20);
      |                           ^~~~~~~
      |                           kvmalloc
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_drv.c:234:25: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  234 |         sdev->vram_save = vmalloc(vram_size << 20);
      |                         ^
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_drv.c:244:17: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
  244 |                 vfree(sdev->vram_save);
      |                 ^~~~~
      |                 kvfree
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_main.c: In function 'smi_driver_load':
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_main.c:399:25: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'? [-Werror=implicit-function-declaration]
  399 |         cdev->regsave = vmalloc(1024);
      |                         ^~~~~~~
      |                         kvmalloc
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_main.c:399:23: warning: assignment to 'struct smi_750_register *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  399 |         cdev->regsave = vmalloc(1024);
      |                       ^
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_main.c: In function 'smi_driver_unload':
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_main.c:447:9: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
  447 |         vfree(cdev->regsave);
      |         ^~~~~
      |         kvfree
```

**Comment by teddywlq** [comment]
Resolved

**Comment by sudipm-mukherjee** [comment]
The Debian build still fails with these errors:
```
  CC [M]  /var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/ddk768/ddk768_help.o
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:64:69: error: expected ‘)’ before string constant
   64 | DEFINE_DEBUGFS_ATTRIBUTE(fops_pwm, debugfs_pwm_get, debugfs_pwm_set, "%llu\n");
      |                                                                     ^~~~~~~~~
      |                                                                     )
```
```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c: In function ‘smi_debugfs_init’:
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:148:9: error: implicit declaration of function ‘debugfs_create_file_unsafe’; did you mean ‘sysfs_create_file_ns’? [-Werror=implicit-function-declaration]
  148 |         debugfs_create_file_unsafe("pwm_ctl", S_IRUGO | S_IWUSR, minor->debugfs_root, &pwm_ctrl, &fops_pwm);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:148:99: error: ‘fops_pwm’ undeclared (first use in this function); did you mean ‘fops_put’?
  148 |         debugfs_create_file_unsafe("pwm_ctl", S_IRUGO | S_IWUSR, minor->debugfs_root, &pwm_ctrl, &fops_pwm);
      |                                                                                                   ^~~~~~~~
```
```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:150:9: error: implicit declaration of function ‘debugfs_create_u32’ [-Werror=implicit-function-declaration]
  150 |         debugfs_create_u32("smi_debug", S_IRUGO | S_IWUSR, minor->debugfs_root, &smi_debug);
      |         ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:155:16: error: implicit declaration of function ‘vzalloc’; did you mean ‘kvzalloc’? [-Werror=implicit-function-declaration]
  155 |         regs = vzalloc(REGS_SIZE * sizeof(struct debugfs_reg32));
      |                ^~~~~~~
      |                kvzalloc
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_debugfs.c:155:43: error: invalid application of ‘sizeof’ to incomplete type ‘struct debugfs_reg32’
  155 |         regs = vzalloc(REGS_SIZE * sizeof(struct debugfs_reg32));
      |                                           ^~~~~~
```
