### ISSUE TITLE
Fails to build with v6.15 and v6.16 kernels

### ISSUE THREAD

**Issue by sudipm-mukherjee** [teddywlq/smifb2#28]
smifb2 fails to build with the following error:

```
smi_mode.c:1098:23: error: initialization of ‘enum drm_mode_status (*)(struct drm_connector *, const struct drm_display_mode *)’ from incompatible pointer type ‘enum drm_mode_status (*)(struct drm_connector *, struct drm_display_mode *)’ [-Wincompatible-pointer-types]
 1098 |         .mode_valid = smi_connector_mode_valid,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
smi_mode.c:1098:23: note: (near initialization for ‘smi_vga_connector_helper_funcs.mode_valid’)
```

Debian Bug: https://bugs.debian.org/1106711
