### ISSUE TITLE
Fails to build with 6.12 kernel

### ISSUE THREAD

**Issue by sudipm-mukherjee** [teddywlq/smifb2#25]
The error is:

```
/var/lib/dkms/smifb2/2.4.0/build/smi_main.c:60:10: error: ‘const struct drm_mode_config_funcs’ has no member named ‘output_poll_changed’
   60 |         .output_poll_changed = drm_fb_helper_output_poll_changed,
      |          ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/smifb2/2.4.0/build/smi_main.c:60:32: error: ‘drm_fb_helper_output_poll_changed’ undeclared here (not in a function)
   60 |         .output_poll_changed = drm_fb_helper_output_poll_changed,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by marafa-sugarcrm** [comment]
same here

**Comment by teddywlq** [comment]
Fixed
