### ISSUE TITLE
Fails to build with v6.8 kernel

### ISSUE THREAD

**Issue by sudipm-mukherjee** [teddywlq/smifb2#19]
`I2C_CLASS_DDC` has been removed in v6.8 kernels and the build now fails:

```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/ddk750/ddk750_hwi2c.c: In function ‘ddk750_AdaptHWI2CInit’:
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/ddk750/ddk750_hwi2c.c:137:32: error: ‘I2C_CLASS_DDC’ undeclared (first use in this function); did you mean ‘I2C_CLASS_SPD’?
  137 |     connector->adapter.class = I2C_CLASS_DDC;
      |                                ^~~~~~~~~~~~~
      |                                I2C_CLASS_SPD
```

**Comment by teddywlq** [comment]
Fixed
