### ISSUE TITLE
Fails to build with v6.11 kernel

### ISSUE THREAD

**Issue by sudipm-mukherjee** [teddywlq/smifb2#23]
Fails to build with the error:

```
/var/lib/dkms/smifb2/2.2.3.4.g1828e79/build/smi_drv.c:9:10: fatal error: drm/drm_fbdev_generic.h: No such file or directory
    9 | #include <drm/drm_fbdev_generic.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```
